docker_api https fix for secured docker
nginx-proxy/acme-companion pull request #673
Opened 2020-06-30 17:13 UTC by alin-o

The certificate path is also needed when docker daemon mode is `tlsverify`

see https://docs.docker.com/engine/security/https/#connecting-to-the-secure-docker-port-using-curl

2020-07-04 00:17 UTC, buchdag commented
Hi.

Thanks for the contribution. Have you tested it ?

Do you think you could add documentation for this feature to your PR ?

2020-07-04 10:40 UTC, alin-o commented
Hi,

I tested this on my own servers, which are configured with daemon mode `tlsverify`, and it works. Before this change, no certificates were ever generated because the `curl` command returned just an error message,

I added a short documentation under `docs/Container-configuration.md`. I hope it is the right place.

2020-07-04 18:06 UTC, buchdag commented
> I added a short documentation under `docs/Container-configuration.md`. I hope it is the right place.

Yep, that's perfect, thanks.

> I tested this on my own servers, which are configured with daemon mode `tlsverify`, and it works.

Okay this is going to be pretty hard to test on Travis.

2024-05-05 21:52 UTC, buchdag requested changes
Somehow I wrote change requests for this PR almost 4 years ago and never pressed the **Submit review** button. 🤦

2026-06-18 08:48 UTC, buchdag commented
Implemented in #1265

2026-06-18 08:48 UTC, closed without merging